---
title: "RNASeq Data Generation"
author: "Nick Waalkes"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

# Load libraries
library(DESeq2)
library(onlineFDR)
library(seqgendiff)
library(compcodeR)
library(dplyr)
```

```{r simulate_data_fct}
generateSequentialCountMatrix <- function(numHyp, varNum, diffExp, nSamples = 5){
  
  # numHyp: ?
  # varNum: ?
  # diffExp: ?
  
  # initialize a list of datasets over time
  synthData <- list()
  
  #describe your conditions
  condVec <- c(rep("control", nSamples), rep("treatment", nSamples)) 
  
  for (i in seq_along(1:numHyp)){
    
    # you need a seed for reproducibility of simulated data
    set.seed(i)
    
    synthData[[i]] <- generateSyntheticData(dataset = "B_625_625", 
                                            n.vars = varNum, 
                                            samples.per.cond = nSamples, 
                                            n.diffexp = diffExp, 
                                            repl.id = 1, 
                                            seqdepth = 1e7, 
                                            fraction.upregulated = 0.5, 
                                            between.group.diffdisp = FALSE, 
                                            filter.threshold.total = -1, # don't understand this
                                            filter.threshold.mediancpm = -1, # don't understand this
                                            fraction.non.overdispersed = 0, 
                                            output.file = "OutputTestSynth.rds")
    
    colnames(synthData[[i]]@count.matrix) <- condVec
  }
  
  # unless you plan on providing a different diffExp for each simulated dataset,
  # we only need to save once
  diffExpressionVec <- synthData[[1]]@variable.annotations$differential.expression

  list(countMatrix = synthData,
       sampleCondition = condVec,
       diffExpression = diffExpressionVec)
}
```

```{r deseq_fct}
DESeqPipeline <- function(countMatrix, conditions) {
  
  colData <- data.frame(condition = conditions) %>%
    mutate(condition = as.factor(condition))
  
  ddsFromMatrix <- DESeqDataSetFromMatrix(countData = countMatrix, 
                                          colData = colData, 
                                          design = ~ condition)
  
  dds <- DESeq(ddsFromMatrix)
  res <- results(dds)
  
  resData <- merge(as.data.frame(res), as.data.frame(counts(dds, normalized = TRUE)), 
                   by = 'row.names', 
                   sort = FALSE)

  resData
}
```

```{r fdr_fct}
control_offlineFDR <- function(pValueVec, diffExpVec, cutoff = 0.05, .method = "BH"){
  # describe func args

  adjP <- p.adjust(pValueVec, method = .method)
  
  n_positives <- sum(adjP < cutoff, na.rm = TRUE)
  n_true_positives <- sum((adjP < cutoff) & diffExpVec, na.rm = TRUE)
  n_false_positives <- sum((adjP < cutoff) & (diffExpVec == 0), na.rm = TRUE)
  fdr <- n_false_positives/n_positives
  tibble(n_positives = n_positives,
         n_true_positives = n_true_positives,
         n_false_positives = n_false_positives,
         fdr = fdr)
}

onlineFDR <- function(pValueMatrix, diff ExpMatrix, cutoff){
  adjP <- SAFFRON(pValueMatrix)
  positives <- 0
  fPositives <- 0
  
  
  print(type(adjP[1]))
  
  for (i in 1:length(adjP)){
    if (adjP[i])
      if (adjP[i] < cutoff){
        positives <- positives + 1
        if (diffExpMatrix[i] == 0) {
          fPositives <- fPositives + 1
        }
      }
  }
  
  fdr <- fPositives / positives
  return(fdr)
}

```

```{r}
syntheticData <- generateSequentialCountMatrix(1, 1000, 100)
res <- DESeqPipeline(syntheticData$countMatrix[[1]]@count.matrix, syntheticData$sampleCondition)
control_offlineFDR(res$pvalue, syntheticData$diffExpression)
```
You should look into a couple of things:

* Why are there NAs in the res?
* Why is the FDP 0.087? This is higher than our nominal threshold of 0.05